export const types = {
	LOGIN_ASYNC: 'LOGIN_ASYNC',
	FINISH_LOADING: 'FINISH_LOADING',
	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	SIGNUP_UP_SUCCESSFUL: 'SIGNUP_UP_SUCCESSFUL',
	LOGOUT: 'LOGOUT',
	SIGNUP_ASYNC: 'SIGNUP_ASYNC',
	SET_USER: 'SET_USER',
	ASYNC_LOGOUT: 'ASYNC_LOGOUT',
}
